window.addEventListener("load",function(){
    let eid ="24880x728x90x4219x_ADSLOT1"; let eidi = eid+"i";
    let ifm = document.createElement("iframe");
        ifm.frameBorder=0;ifm.scrolling= "no";ifm.width= "728";ifm.height= "90";ifm.id=eidi;
        document.getElementById(eid).style.maxWidth = eid.split("x")[1] + "px";
        document.getElementById(eid).style.maxHeight = eid.split("x")[2] + "px";
    document.getElementById(eid).appendChild(ifm);
    let doc = document.getElementById(eidi).contentWindow.document;
    doc.write("<head><script type='text/javascript' src='https://cdn.pixfuture.com/djax_elastic.js'> <\/script><script type='text/javascript' src='https://cdn.pixfuture.com/prebid4.19.0.js?v=3'></script><\/head><div id=\""+eid+"\"></div><style>html,body{border: 0px;margin: 0px;padding: 0px;}</style>");
    var ibeyn = '';
ibeyn += "<"+"script type=\"text/javascript\">\n";
ibeyn += "function findCMP() {let f = window;let cmpFrame;let cmpFunction;while (!cmpFrame) {try {if (typeof f.__tcfapi === \'function\' || typeof f.__cmp === \'function\') {if (typeof f.__tcfapi === \'function\') {cmpVersion = 2;cmpFunction = f.__tcfapi;} else {cmpVersion = 1;cmpFunction = f.__cmp;}cmpFrame = f;break;}} catch (e) { }try {if (f.frames[\'__tcfapiLocator\']) {cmpVersion = 2;cmpFrame = f;break;}} catch (e) { }try {if (f.frames[\'__cmpLocator\']) {cmpVersion = 1;cmpFrame = f;break;}} catch (e) { }if (f === window.top) break;f = f.parent;}return {cmpFrame,cmpFunction};}\n";
ibeyn += "let { cmpFrame, cmpFunction } = findCMP();\n";
ibeyn += "var consent_module = \"\";\n";
ibeyn += "var file_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
ibeyn += "var t = 3;\n";
ibeyn += "var tout = 2000;\n";
ibeyn += "var site_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
ibeyn += "var org_site_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
ibeyn += "var mainDiv =\"pf-24880x728x90x4219x_ADSLOT1\";\n";
ibeyn += "var parent_ad_width = 728;\n";
ibeyn += "var parent_ad_height = 90;\n";
ibeyn += "if(parent_ad_width == 728 && parent_ad_height == 90) {\n";
ibeyn += "var flag_used = true;\n";
ibeyn += "} else {\n";
ibeyn += "var flag_used = false;\n";
ibeyn += "}\n";
ibeyn += "var int = new Array();\n";
ibeyn += "var pbjs = pbjs || {};\n";
ibeyn += "pbjs.que = pbjs.que || [];\n";
ibeyn += "var che = \"728\";\n";
ibeyn += "var sz = [\"24880x728x90x4219x_ADSLOT1\"];\n";
ibeyn += "var bz = [\"banner\"];\n";
ibeyn += "int[0]={\"24880x728x90x4219x_ADSLOT1\":{\"url\":\"<"+"script type=\\\"text\\/javascript\\\">var innerWidth = 1600;<"+"\\/script> <"+"!--pixfuture bid551--> <"+"script type=\\\"text\\/javascript\\\">google_ad_client = \\\"ca-pub-1575911585432548\\\"; google_ad_slot = \\\"3157381981\\\"; google_ad_width = 728; google_ad_height = 90; <"+"\\/script> <"+"script type=\\\"text\\/javascript\\\" src=\\\"\\/\\/pagead2.googlesyndication.com\\/pagead\\/show_ads.js\\\"> <"+"\\/script>\",\"is_house\":0,\"cpm\":0.07999999821186066,\"floor_price\":0,\"width\":\"728\",\"height\":\"90\",\"code\":\"4219\",\"zoneid\":\"24880\",\"adUnitCode\":\"24880x728x90x4219x_ADSLOT1\",\"type\":\"intbanner\",\"third_share\":\"70\",\"int_share\":\"70\",\"passback\":\"<"+"script async src=\\\"https:\\/\\/pagead2.googlesyndication.com\\/pagead\\/js\\/adsbygoogle.js\\\"><"+"\\/script> <"+"!-- Display 728x90 --> <"+"ins class=\\\"adsbygoogle\\\" style=\\\"display:inline-block;width:728px;height:90px\\\" data-ad-client=\\\"ca-pub-3732773600888178\\\" data-ad-slot=\\\"1410653048\\\"><"+"\\/ins> <"+"script> (adsbygoogle = window.adsbygoogle || []).push({}); <"+"\\/script>\",\"campaignId\":3,\"bannerId\":14}};\n";
ibeyn += "var waypl = [\n";
ibeyn += "/*header-bidding-bidders*/\n";
ibeyn += "{\n";
ibeyn += "code:\"24880x728x90x4219x_ADSLOT1\",\n";
ibeyn += "mediaTypes: {banner: { sizes:[728,90]}},\n";
ibeyn += "bids: [{bidder : \"conversant\",params: {\"site_id\": \"202603\"}},{bidder : \"improvedigital\",params: {\"bidFloor\": 0.1,\"placementId\": 22292112}},{bidder : \"openx\",params: {\"customParams\": { \"myKeyword\": \"html,icons,free,download,png,svg\",\"myOtherKeyword\": [\'html\',\'icons\',\'free\',\'download\',\'png\',\'svg\']},\"unit\": \"540580842\",\"delDomain\": \"pixfuture2-d.openx.net\"}},{bidder : \"smartadserver\",params: {\"target\": \"html=html|icons=icons|free=free|download=download|png=png|svg=svg\",\"formatId\": 0,\"pageId\": 1240155,\"siteId\": \"354470\"}},{bidder : \"33across\",params: {\"siteId\": \"azC7qard4r6OkMaKlId8sQ\",\"productId\": \"siab\"}},{bidder : \"synacormedia\",params: {\"seatId\": \"pixfuture\",\"placementId\": \"84884\",\"bidfloor\": 0.1,\"pos\": 1}},{bidder : \"appnexus\",params: {\"keywords\": { \"myKeyword\": \"html,icons,free,download,png,svg\",\"myOtherKeyword\": [\'html\',\'icons\',\'free\',\'download\',\'png\',\'svg\']},\"placementId\": 15106105}},{bidder : \"aol\",params: {\"pos\": \"pixfuture_network_news_728x90\",\"dcn\": \"8a969105017575db4f32dc2eda5c0067\"}},{bidder : \"aol\",params: {\"network\": \"9834\",\"placement\": \"3344885\"}},{bidder : \"pubmatic\",params: {\"dctr\": \"html=html|icons=icons|free=free|download=download|png=png|svg=svg\",\"publisherId\": \"158127\",\"adSlot\": \"2069654\",\"kadfloor\": \"0.75\"}}]\n";
ibeyn += "}];\n";
ibeyn += "pbjs.que.push(function(){\n";
ibeyn += "pbjs.setConfig({\n";
ibeyn += "userSync: {\n";
ibeyn += "filterSettings: {\n";
ibeyn += "iframe: {\n";
ibeyn += "bidders: \"*\",\n";
ibeyn += "filter: \"include\"\n";
ibeyn += "}\n";
ibeyn += "},\n";
ibeyn += "syncsPerBidder: 0,\n";
ibeyn += "syncDelay: 1000\n";
ibeyn += "},\n";
ibeyn += "schain: {\n";
ibeyn += "validation: \"strict\",\n";
ibeyn += "config: {\n";
ibeyn += "ver:\"1.0\",\n";
ibeyn += "complete: 1,\n";
ibeyn += "nodes: [\n";
ibeyn += "{\n";
ibeyn += "asi:\"pixfuture.com\",\n";
ibeyn += "sid:\"4219\",\n";
ibeyn += "hp:1\n";
ibeyn += "}\n";
ibeyn += "]\n";
ibeyn += "}\n";
ibeyn += "},\n";
ibeyn += "pubcid: {expInterval: 525600}      })\n";
ibeyn += "pbjs.bidderSettings = {conversant: {\n";
ibeyn += "bidCpmAdjustment: function (bidCpm, bid) {\n";
ibeyn += "return bidCpm * 0.87;\n";
ibeyn += "}\n";
ibeyn += "},synacormedia: {\n";
ibeyn += "bidCpmAdjustment: function (bidCpm, bid) {\n";
ibeyn += "return bidCpm * 0.85;\n";
ibeyn += "}\n";
ibeyn += "}};\n";
ibeyn += "if (!cmpFrame) {\n";
ibeyn += "console.log(\"CMP IS NOT FOUND!!!\");\n";
ibeyn += "}else{\n";
ibeyn += "pbjs.setConfig({\n";
ibeyn += "consentManagement: {gdpr: {cmpApi: \"iab\",timeout: 2000},usp: {timeout: 500}}\n";
ibeyn += "});\n";
ibeyn += "console.log(\"CMP IS FOUND\");\n";
ibeyn += "}\n";
ibeyn += "pbjs.requestBids({\n";
ibeyn += "adUnits:waypl,\n";
ibeyn += "bidsBackHandler: function(bidResponses) {\n";
ibeyn += "try {\n";
ibeyn += "//console.log(dome(waypl));\n";
ibeyn += "dome(waypl, false);\n";
ibeyn += "} catch (e) {\n";
ibeyn += "console.log(e);\n";
ibeyn += "console.log(\"retry sending request!!!!!!!\");\n";
ibeyn += "setTimeout(function(){\n";
ibeyn += "dome(waypl, false);\n";
ibeyn += "}, 300);\n";
ibeyn += "}\n";
ibeyn += "},\n";
ibeyn += "timeout: 2000,\n";
ibeyn += "});\n";
ibeyn += "});\n";
ibeyn += "var zone_id         = 24880;\n";
ibeyn += "function loadScript(url, callback) {\n";
ibeyn += "var script = document.createElement(\"script\")\n";
ibeyn += "script.type = \"text/javascript\";\n";
ibeyn += "if (script.readyState) {\n";
ibeyn += "script.onreadystatechange = function() {\n";
ibeyn += "if (script.readyState == \"loaded\" || script.readyState == \"complete\") {\n";
ibeyn += "script.onreadystatechange = null;\n";
ibeyn += "callback()\n";
ibeyn += "}\n";
ibeyn += "}\n";
ibeyn += "} else {\n";
ibeyn += "script.onload = function() {\n";
ibeyn += "callback()\n";
ibeyn += "}\n";
ibeyn += "}\n";
ibeyn += "script.src = url;\n";
ibeyn += "document.getElementsByTagName(\"head\")[0].appendChild(script)\n";
ibeyn += "}\n";
ibeyn += "<"+"/script>\n";
doc.write(ibeyn);
doc.close();});